apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
namePrefix: prod-

# cd k8s/overlays/prod
# kustomize edit add secret sl-demo-app --from-literal=db-password=12345

secretGenerator:
- literals:
  - db-password=12345
  name: sl-demo-app
  type: Opaque

# TAG_VERSION=3.4.5
# cd k8s/overlays/prod
# kustomize edit set image foo/bar=foo/bar:$TAG_VERSION

images:
- name: foo/bar
  newName: foo/bar
  newTag: 3.4.5
labels:
- includeSelectors: true
  pairs:
    app: my-app
    env: prod
patches:
- path: custom-env.yaml
- path: replica-and-rollout-strategy.yaml
- path: database-secret.yaml

resources:
- ../../../base
- ingress.yaml
