apiVersion: apps/v1
kind: Deployment
metadata:
  name: sl-demo-app
  namespace: prod
spec:
  replicas: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
